# Configuration for T-Kits Plugin

###########################################################
#                      DATABASE SETTINGS                  #
###########################################################
database:
  enabled: false           # Enable MySQL database storage? (true/false)
  host: "localhost"        # MySQL database host
  port: 3306               # MySQL database port
  database_name: "tkits"   # Name of the database to use
  username: "root"         # MySQL username
  password: "password"     # MySQL password (leave empty if no password)

  # Advanced Connection Pool Settings (HikariCP)
  pool_size: 10             # Maximum number of connections in the pool
  idle_timeout: 300000      # время простоя (5 minutes in milliseconds)
  connection_timeout: 10000 # Connection timeout (10 seconds in milliseconds)

  # Auto-Save Settings (for YAML and MySQL)
  auto-save: true          # Enable automatic saving of data? (true/false)
  auto-save-time: 5        # Auto-save interval in minutes


###########################################################
#                  BROADCAST MESSAGE SETTINGS             #
###########################################################
broadcast-messages:
  loadkit-enabled: false               # Enable broadcast message when a kit is loaded? (true/false)
  loadkit-prefix: "&8[&3T&bKits&8] &7" # Prefix for the load kit broadcast message
  loadkit-suffix: " &7loaded a &bKit"  # Suffix for the load kit broadcast message

  open-kitroom-enabled: false                     # Enable broadcast message when Kit Room is opened? (true/false)
  open-kitroom-prefix: "&8[&3T&bKits&8] &7"       # Prefix for the Kit Room open broadcast
  open-kitroom-suffix: " &7opened the &bKit Room" # Suffix for Kit Room open broadcast

  premadekit-enabled: true                        # Enable broadcast message when Premade Kit is loaded? (true/false)
  premadekit-prefix: "&8[&3T&bKits&8] &7"         # Prefix for Premade Kit load broadcast
  premadekit-suffix: " &7loaded the premade kit"  # Suffix for Premade Kit load broadcast


###########################################################
#                    PLAYER MESSAGE SETTINGS              #
###########################################################
player-messages:
  motd-enabled: false       # Enable Message of the Day (MOTD) on player join? (true/false)
  motd: # MOTD messages (displayed in action bar)
    - "&bUse &3/kit &bto access your kits."
  motd-delay: 5             # Delay in seconds before MOTD is displayed

  info-enabled: true        # Enable info messages in Kit Menu? (true/false)
  info: # Info messages for Kit Menu
    - "&7Left-Click &bKit Chest &7to Load."    # Information line 1
    - "&7Right-Click &bKit Chest &7to Edit."   # Information line 2


###########################################################
#                     SOUND EFFECT SETTINGS               #
###########################################################
sounds:
  kit-load: "ENTITY_EXPERIENCE_ORB_PICKUP" # Sound played when a kit is loaded
  kit-save: "BLOCK_NOTE_BLOCK_PLING"       # Sound played when a kit is saved
  menu-click: "UI_BUTTON_CLICK"            # Sound for menu button clicks
  error: "ENTITY_VILLAGER_NO"              # Sound for error feedback
  success: "ENTITY_PLAYER_LEVELUP"         # Sound for success feedback


###########################################################
#                      WORLD RESTRICTIONS                 #
###########################################################
world-config:
  disable-worlds: false     # Disable kit usage in specific worlds? (true/false)
  worlds: # List of worlds where kits are disabled (if disable-worlds: true)
    - "world_nether"        # Example world: Nether
    - "world_the_end"       # Example world: The End


###########################################################
#                       KIT CONFIGURATION                 #
###########################################################
kit-config:
  disable-echest: false    # Disable Ender Chest functionality in kits? (true/false)


###########################################################
#                    INVENTORY MANAGEMENT                 #
###########################################################
inventory-management:
  regear-enabled: true     # Enable /regear command for players? (true/false)
  arrange-enabled: true    # Enable /arrange or /rearrange command for players? (true/false)


###########################################################
#                     KIT SHARE CODE SETTINGS             #
###########################################################
share-code-settings:
  one-time-codes: true     # Kit share codes valid for single use only? (true/false)
  code-expiry-minutes: 5   # Kit share code expiration time in minutes